name: project66
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: android
  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type

  day_night_time_picker:
  introduction_screen: ^3.1.14
  android_power_manager: ^1.0.0
  group_button: ^5.3.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.7.0
  http: ^1.2.2
  bottom_navy_bar:
  flutter_keyboard_visibility: ^6.0.0
  shared_preferences: ^2.2.3
  lottie: ^3.1.0
  flutter_screenutil: ^5.9.0
  pinput: ^4.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.1
  url_launcher: ^6.2.6
  logger: ^2.3.0
  dropdown_button2: ^2.3.9
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  cloud_firestore: ^5.3.0
  geolocator: ^11.0.0
  intl: ^0.19.0
  collection: ^1.18.0
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_local_notifications: ^17.1.2
  package_info_plus: ^8.0.0
  flutter_async_autocomplete: ^0.1.1
  multi_select_flutter: ^4.1.3
  percent_indicator: ^4.2.3
  hive: ^2.2.3
  internet_connection_checker: ^1.0.0+1
  awesome_dialog: ^3.2.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  geocoding: ^3.0.0
  dotted_border: ^2.1.0
  easy_stepper: ^0.8.5
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  crypto: ^3.0.3
  card_swiper : ^3.0.1
  google_maps_flutter : ^2.7.0
  firebase_remote_config: ^5.0.2
  widget_to_marker: ^1.0.6
  flutter_inappwebview:
  go_router: ^14.2.0
  simple_progress_indicators:
  fl_chart: ^0.68.0
  syncfusion_flutter_charts:
  syncfusion_flutter_sliders: ^26.2.7
  file_picker:
  permission_handler: ^11.3.1
  flutter_cached_pdfview: ^0.4.2
  win32: ^5.5.4
  archive: ^3.6.1
  google_mlkit_text_recognition: ^0.13.0

  excel: any

  syncfusion_localizations:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/temp/
    - assets/
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
    - family: cairoBold
      fonts:
        - asset: assets/fonts/cairo_bold.ttf
    - family: cairoSemiBold
      fonts:
          - asset: assets/fonts/cairo_semi_bold.ttf

flutter_intl:
  enabled: true
