name: project66
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: android
  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type


  group_button: ^5.3.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.7.0
  http: ^1.2.2


  shared_preferences: ^2.2.3
  lottie: ^3.1.0
  flutter_screenutil: ^5.9.0

  image_picker: ^1.1.1

  logger: ^2.3.0

  firebase_core: ^3.4.0
  cloud_firestore: ^5.3.0

  intl: ^0.19.0
  collection: ^1.18.0
  path_provider: ^2.1.3
  path: ^1.9.0

  awesome_dialog: ^3.2.1
  go_router: ^14.2.0
  hive_flutter:

  win32: ^5.5.4
  dropdown_button2:
  permission_handler:
  package_info_plus:
  archive: ^3.6.1
  google_mlkit_text_recognition: ^0.13.0

  excel: any

  syncfusion_localizations:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/temp/
    - assets/
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
    - family: cairoBold
      fonts:
        - asset: assets/fonts/cairo_bold.ttf
    - family: cairoSemiBold
      fonts:
        - asset: assets/fonts/cairo_semi_bold.ttf

flutter_intl:
  enabled: true
